TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 16
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
  CHECKPOINT_FILE_PATH: '../MViTv2_B_32x3_k400_f304025456.pyth'
  CHECKPOINT_EPOCH_RESET: True
DATA:
  USE_OFFSET_SAMPLING: True
  DECODING_BACKEND: pyav
  NUM_FRAMES: 6 # watch out
  SAMPLING_RATE: 5 # watch out 
  STRIDE: 6 # watch out
  TRAIN_JITTER_SCALES: [438, 548]
  TRAIN_CROP_SIZE: 384
  TEST_CROP_SIZE: 384
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: '/workspace/AICity2023/data/A2_raw_2.5D' # watch out
  PATH_EXTRACT: /workspace/AICity2023/data/extract_feature_A2_MVit_mean5fold_1s # watch out
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
  RANDOM_FLIP: False
MVIT:
  ZERO_DECAY_POS_CLS: False
  USE_ABS_POS: False
  REL_POS_SPATIAL: True
  REL_POS_TEMPORAL: True
  DEPTH: 24
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPPATH_RATE: 0.3
  NORM: "layernorm"
  MODE: "conv"
  CLS_EMBED_ON: False
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  POOL_KVQ_KERNEL: [3, 3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_Q_STRIDE: [[0, 1, 1, 1], [1, 1, 1, 1], [2, 1, 2, 2], [3, 1, 1, 1], [4, 1, 1, 1], [5, 1, 2, 2], [6, 1, 1, 1], [7, 1, 1, 1], [8, 1, 1, 1], [9, 1, 1, 1], [10, 1, 1, 1], [11, 1, 1, 1], [12, 1, 1, 1], [13, 1, 1, 1], [14, 1, 1, 1], [15, 1, 1, 1], [16, 1, 1, 1], [17, 1, 1, 1], [18, 1, 1, 1], [19, 1, 1, 1], [20, 1, 1, 1], [21, 1, 2, 2], [22, 1, 1, 1], [23, 1, 1, 1]]
  DROPOUT_RATE: 0.0
  DIM_MUL_IN_ATT: True
  RESIDUAL_POOLING: True
AUG:
  NUM_SAMPLE: 2
  ENABLE: True
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: linear
  RE_PROB: 0.25
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: True
  ALPHA: 0.4
  CUTMIX_ALPHA: 0.4
  PROB: 1.0
  SWITCH_PROB: 0.5
  LABEL_SMOOTH_VALUE: 0.1
SOLVER:
  ZERO_WD_1D_PARAM: True
  BASE_LR_SCALE_NUM_SHARDS: True
  CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.0005
  COSINE_AFTER_WARMUP: True
  COSINE_END_LR: 1e-6
  WARMUP_START_LR: 1e-6
  WARMUP_EPOCHS: 35.0
  LR_POLICY: cosine
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  OPTIMIZING_METHOD: adamw
  COSINE_AFTER_WARMUP: True
MODEL:
  NUM_CLASSES: 16
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
  # EMA_DECAY: 0.95
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  NUM_SPATIAL_CROPS: 1
  NUM_ENSEMBLE_VIEWS: 5
  EXTRACT_FEATURE: True
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0

WEIGHT:
  DASHBOARD: ['/workspace/AICity2023/checkpoint_MVit/fold0/Dashboard/checkpoint_epoch_00107.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold1/Dashboard/checkpoint_epoch_00105.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold2/Dashboard/checkpoint_epoch_00192.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold3/Dashboard/checkpoint_epoch_00046.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold4/Dashboard/checkpoint_epoch_00060.pyth']  
  REARVIEW: ['/workspace/AICity2023/checkpoint_MVit/fold0/Rearview/checkpoint_epoch_00197.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold1/Rearview/checkpoint_epoch_00116.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold2/Rearview/checkpoint_epoch_00101.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold3/Rearview/checkpoint_epoch_00060.pyth',
              '/workspace/AICity2023/checkpoint_MVit/fold4/Rearview/checkpoint_epoch_00175.pyth']
  RIGHT_SIDE_WINDOW: ['/workspace/AICity2023/checkpoint_MVit/fold0/Right_side_window/checkpoint_epoch_00197.pyth',
                      '/workspace/AICity2023/checkpoint_MVit/fold1/Right_side_window/checkpoint_epoch_00107.pyth',
                      '/workspace/AICity2023/checkpoint_MVit/fold2/Right_side_window/checkpoint_epoch_00180.pyth',
                      '/workspace/AICity2023/checkpoint_MVit/fold3/Right_side_window/checkpoint_epoch_00049.pyth',
                      '/workspace/AICity2023/checkpoint_MVit/fold4/Right_side_window/checkpoint_epoch_00133.pyth']